**Test Cases**

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-c3ow{border-color:inherit;text-align:center;vertical-align:top}
.tg .tg-7btt{border-color:inherit;font-weight:bold;text-align:center;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-7btt">Test Cases No.</th>
    <th class="tg-7btt">Descripton</th>
    <th class="tg-7btt">Input</th>
    <th class="tg-7btt">Expected output</th>
    <th class="tg-7btt">Actual output</th>
    <th class="tg-7btt">result</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-c3ow">1</td>
    <td class="tg-c3ow">Print sub strings<br></td>
    <td class="tg-c3ow">abaca<br></td>
    <td class="tg-c3ow">a ab aba abaca b ba <br>bac baca a ac aca c ca a</td>
    <td class="tg-c3ow">a ab aba abaca b ba <br>bac baca a ac aca c ca a</td>
    <td class="tg-c3ow">Pass</td>
  </tr>
  <tr>
    <td class="tg-c3ow">2</td>
    <td class="tg-c3ow">Print Sub Strings with length k<br></td>
    <td class="tg-c3ow">3</td>
    <td class="tg-c3ow">aba bac aca</td>
    <td class="tg-c3ow">aba bac aca<br></td>
    <td class="tg-c3ow">Pass</td>
  </tr>
  <tr>
    <td class="tg-c3ow">3</td>
    <td class="tg-c3ow">Print substring of length k<br>with n distinct characters<br></td>
    <td class="tg-c3ow">2</td>
    <td class="tg-c3ow">aba aca</td>
    <td class="tg-c3ow">aba aca<br></td>
    <td class="tg-c3ow">Pass</td>
  </tr>
  <tr>
    <td class="tg-c3ow">4</td>
    <td class="tg-c3ow">Print substring of maximum length<br>with n distinct characters<br></td>
    <td class="tg-c3ow">2</td>
    <td class="tg-c3ow">aba aca</td>
    <td class="tg-c3ow">aba aca<br></td>
    <td class="tg-c3ow">Pass</td>
  </tr>
  <tr>
    <td class="tg-c3ow">5</td>
    <td class="tg-c3ow">Palindromic sub strings</td>
    <td class="tg-c3ow">abaca</td>
    <td class="tg-c3ow">a aba b a aca c a</td>
    <td class="tg-c3ow">a aba b a aca c a</td>
    <td class="tg-c3ow">Pass</td>
  </tr>
  <tr>
    <td class="tg-c3ow">6</td>
    <td class="tg-c3ow">Input for numbers<br>Print substrings<br></td>
    <td class="tg-c3ow">12134</td>
    <td class="tg-c3ow">1 12 121 1213 12134 2 21 213<br>2134 1 13 134 3 34 4<br></td>
    <td class="tg-c3ow">1 12 121 1213 12134 2 21 213<br>2134 1 13 134 3 34 4<br></td>
    <td class="tg-c3ow">pass</td>
  </tr>
  <tr>
    <td class="tg-c3ow">7</td>
    <td class="tg-c3ow">Print Sub Strings with length k</td>
    <td class="tg-c3ow">3</td>
    <td class="tg-c3ow">121 213 134</td>
    <td class="tg-c3ow">121 213 134</td>
    <td class="tg-c3ow">Pass</td>
  </tr>
  <tr>
    <td class="tg-c3ow">8</td>
    <td class="tg-c3ow">Print substring of length k<br>with n distinct characters<br></td>
    <td class="tg-c3ow">1</td>
    <td class="tg-c3ow">There no substrings with 1 distinct<br>characters in 3 length substring<br></td>
    <td class="tg-c3ow">There no substrings with 1 distinct<br><br>characters in 3 length substring</td>
    <td class="tg-c3ow">Pass</td>
  </tr>
  <tr>
    <td class="tg-c3ow">9</td>
    <td class="tg-c3ow">Print palidromic sub strings</td>
    <td class="tg-c3ow">12134</td>
    <td class="tg-c3ow">1 121 2 1 3 4</td>
    <td class="tg-c3ow">1 121 2 1 3 4</td>
    <td class="tg-c3ow">Pass</td>
  </tr>
</tbody>
</table>